version: "3"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - TZ
    restart: unless-stopped
    ports:
      - 35432:5432
    volumes:
      - ./db/postgresql/data:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d

volumes:
  database:
    driver: local
